config/routes.rb
Rails.application.routes.draw do
  get 'home/salud'

 get 'bike/index'
 
 get 'accesory_part/index'

 get 'bike/index'

 resources :products

 resources :sellers

 resources :sellers

  devise_for :users, :controllers =>{:registrations =>"my_devise/registrations"}

  root to: 'home#index'
  
  get 'catalog/index'
  
  resources :products

  resources :inventories

  resources :sales

  resources :items

  resources :clients

  resources :contract_histories

  resources :articles

  resources :equipment

  resources :bikes

  resources :accesory_parts

  get "/:page" => "static_controller#show"

end

app/models/seller.rb
class Seller < ActiveRecord::Base


  validates_presence_of :username, :message => " no puede ser un campo vacio"
  validates_presence_of :userLastName, :message => " no puede ser un campo vacio"
  validates_presence_of :document , :message => " no puede ser un campo vacio"
  validates_uniqueness_of :document , :message => " ya ha sido registrado "
  validates_length_of :document, :within => 8..11 
  validates_presence_of :telephone, :message => " no puede ser un campo vacio"
  validates_length_of :telephone, :within => 6..20
  validates_presence_of :email, :message => " no puede ser un campo vacio"
  validates_presence_of :password, :message => " no puede ser un campo vacio"


	def dataSellers
		"#{document}: #{username}  #{userLastName}"
	end

end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
   #@sellers = User.find(:all, :conditions => { :userType => 'Seller' })
   @sellers = Seller.all
   respond_to do |format|
    format.html
    format.pdf do
      generateReport(@sellers)
    end
  end
end

def show
  @sales = Sale.where(:sellerId => @seller.personId)
end

def new
  @seller = Seller.new

end

def edit
  @reset=false
end

def create
  @seller = Seller.new(seller_params)
  @seller.username=seller_params[:username].titleize
  @seller.userLastName=seller_params[:userLastName].titleize
  @seller.personId= User.all.count+1
  @seller.userType='Seller'
  @seller.status = 1
  @seller.password = "#{@seller.username}.#{@seller.userLastName}".downcase.gsub(/\s+/, "")
  @seller.save
  @user  =  User.new(
    :personId => @seller.personId,
    :username => @seller.username,
    :email =>  @seller.email , 
    :userLastName =>@seller.userLastName,
    :document => @seller.document,
    :telephone => @seller.telephone,
    :userType => @seller.userType,
    :status => @seller.status,
    :password =>  @seller.password,
    :password_confirmation => @seller.password)
  @user.save 
  respond_to do |format|
    if @user.save
      format.html { redirect_to @seller, notice: 'Vendedor creado correctamente.' }
      format.json { render :show, status: :created, location: @seller }
    else
      format.html { render :new }
      format.json { render json: @seller.errors, status: :unprocessable_entity }
    end
  end

end

def update

  @seller.update(seller_params)
  passwd="#{@seller.username}.#{@seller.userLastName}".downcase.gsub(/\s+/, "")
  if @reset==false
    @user  =  User.update(@seller.personId,
      :username => @seller.username,
      :email =>  @seller.email , 
      :userLastName =>@seller.userLastName,
      :document => @seller.document,
      :telephone => @seller.telephone)
  else 
    @user  =  User.update(@seller.personId,
      :username => @seller.username,
      :email =>  @seller.email , 
      :userLastName =>@seller.userLastName,
      :document => @seller.document,
      :telephone => @seller.telephone,
      :password => passwd,
      :password_confirmation=>passwd)
  end
  @user.save 
  respond_to do |format|
    if @user.save
      format.html { redirect_to @seller, notice: 'Vendedor actualizado correctamente.' }
      format.json { render :show, status: :created, location: @seller }
    else
      format.html { render :new }
      format.json { render json: @seller.errors, status: :unprocessable_entity }
    end
  end

end

def destroy
  #@seller.destroy
  respond_to do |format|
   if @seller.status==true
    format.html { redirect_to sellers_url, notice: 'El Vendedor ha sido deshabilitado.' }
    query="update users set status = 0 where personId="+@seller.personId.to_s
    @users=ActiveRecord::Base.connection.execute(query)
    @seller.status=false
  else
    format.html { redirect_to sellers_url, notice: 'El Vendedor ha sido habilitado.' }
    query="update users set status = 1 where personId="+@seller.personId.to_s
    @users=ActiveRecord::Base.connection.execute(query)
    @seller.status=true
  end
  @seller.save
  format.json { head :no_content }
end

end


end

private
def set_seller
  @seller = Seller.find(params[:id])
end

def seller_params
  params.require(:seller).permit(:personId, :document, :username, :userLastName, :email, :password, :password_confirmation, :telephone, :userType, :status)
end
def generateReport(elements)
  pdf = PDF::Writer.new
  pdf.select_font "Times-Roman"
  pdf.image "public/images/logo.jpg", :justification => :center, :resize => 0.4
  pdf.text "Reporte de Vendedores", :font_size => 40, :justification => :center
  pdf.text "Generado el "+ (Time.now()).strftime(" %b %d, %Y").to_s, :font_size => 15, :justification => :center
  elements.each do |item|  
    pdf.text "______________________________________________________", :font_size=>20 , :justification => :center
    pdf.text " "
    pdf.text "ID PERSONA: "+ item.id.to_s, :font_size =>15
    pdf.text "DOCUMENTO: "+item.document.to_s, :font_size => 15
    pdf.text "NOMBRE: " +item.username.to_s, :font_size => 15
    pdf.text "APELLIDO: "+ item.userLastName.to_s, :font_size => 15
    pdf.text "TELEFONO: "+ item.telephone.to_s, :font_size => 15
    if item.status==true 
      pdf.text "ESTADO: Habilitado", :font_size => 15, :justification => :rigth
    else
      pdf.text "ESTADO: Deshabilitado", :font_size => 15, :justification => :rigth
    end
  end
  pdf.render
  send_data pdf.render, :filename => 'Vendedores.pdf', :type => 'application/pdf', :disposition => 'inline'
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
<% if @seller.errors.any? %>
<div class="row">
  <div class="small-8 large-centered columns">
    <div data-alert class="alert-box alert radius">
      <%= pluralize(@seller.errors.count, "error") %> no permite guardar el vendedor
      <ul>
        <% @seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <a href="#" class="close">&times;</a>

    </div>
  </div>
</div>
<% end %>  
<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Documento</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :document, autofocus: true, :required =>true, :pattern=>'[0-9]{8,11}', :maxlength=>11%>
      </div>
    </div>
  </div>
</div>

<p>            </p>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Nombre</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :username, :required =>true, :maxlength =>50 %>
      </div>
    </div>
  </div>
</div>

<p>            </p>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Apellidos</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :userLastName, :required =>true, :maxlength =>50 %>
      </div>
    </div>
  </div>
</div>

<p>            </p>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Numero telefonico</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :telephone, :required =>true, :maxlength =>20, :pattern=>'.{6,20}' %>
      </div>
    </div>
  </div>
</div>

<p>            </p>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Correo electronico</label>
      </div>
      <div class="small-9 columns">
        <%= f.email_field :email, :required =>true, :maxlength =>50, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
      </div>
    </div>
  </div>
</div>



  
</div>
<p></p>
<div class="row">
  <div class="small-4 large-centered columns"><%= f.submit "Guardar", class: "button success radius" %>
  </div>
</div>
<p>            </p>
<% end %>

app/views/sellers/edit.html.erb
<div class="panel ">
	<div class="row">
		<div class="large-6 columns">
			<h2>Editar Vendedor</h2>
		</div>
	</div>

	<%= form_for(@seller) do |f| %>
	<% if @seller.errors.any? %>
	<div class="row">
		<div class="small-8 large-centered columns">
			<div data-alert class="alert-box alert radius">
				<%= pluralize(@seller.errors.count, "error") %> no permite guardar la noticia
				<ul>
					<% @seller.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
				<a href="#" class="close">&times;</a>
			</div>
		</div>
	</div>
	<% end %>  
	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Documento</label>
				</div>
				<div class="small-9 columns">
					<%= f.number_field :document, autofocus: true %>
				</div>
			</div>
		</div>
	</div>

	<p>            </p>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Nombre</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :username %>
				</div>
			</div>
		</div>
	</div>

	<p>            </p>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Apellidos</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :userLastName %>
				</div>
			</div>
		</div>
	</div>

	<p>            </p>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Numero telefonico</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :telephone %>
				</div>
			</div>
		</div>
	</div>

	<p>            </p>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Correo electronico</label>
				</div>
				<div class="small-9 columns">
					<%= f.email_field :email %>
				</div>
			</div>
		</div>
	</div>
	<p></p>
	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Reiniciar contraseña</label>
				</input>
			</div>
				<div class="small-9 columns">
					<input type="checkbox" id="remember" name="remember"  onclick="validate()" />
					</input>
				</div>
			</div>
		</div>
	</div>
<p></p>



<p></p>
<div class="row">
	<div class="small-4 large-centered columns"><%= f.submit "Guardar", class: "button success radius" %>
	</div>
</div>
<p>            </p>
<% end %>

<div class="row">
	<div class="large-9 columns">
		<div class="actions">
			<%= link_to '← Volver', sellers_path %>
		</div>
	</div>
</div>
</div>

<script type="text/javascript">
function validate() {
	if (document.getElementById('remember').checked) {
		alert("La contraseña del Vendedor será modificada a nombre.usuario");
		<%= @reset=true %>
	} else {
		alert("La contraseña anterior del vendedor se conservara");
		<%= @reset=false %>
	}
}
</script>

app/views/sellers/index.html.erb
<div class="panel">
  <%if @sellers.empty?  %>
  <p>            </p>
  <div class="row">
    <div class="small-8 large-centered columns">
      <h1 align="center">Aun no se ha registrado ningun vendedor</h1>
    </div>
    <div class="small-2 large-centered columns"><%= link_to "Crear Vendedor", new_seller_path, class: "radius button center"%>  </div>
  </div>
  <%else%>
  <div class="row">
    <div class="small-12 large-centered columns">
      <h1>Lista de vendedores - La Ciclería</h1>
    </div>
    <div class="small-12 large-centered columns">
      <table>
        <thead>
          <tr>
            <th width="50">Id</th>
            <th width="20">Numero Documento</th>
            <th width="300">Nombre</th>
            <th width="200">Correo electronico</th>
            <th width="100">Nro Telefonico</th>
            <th width="220">Administración de vendedores</th>
          </tr>
        </thead>

        <tbody>
          <% @sellers.each do |seller| %>
          <tr>
            <td><%= seller.personId %></td>
            <td><%= seller.document %></td>
            <td><%= seller.username %>  <%= seller.userLastName %></td>
            <td><%= seller.email %></td>
            <td><%= seller.telephone %></td>
            <td>
                <%= link_to 'Ver', seller , class: "small button success centered"%>
                <%= link_to 'Editar', edit_seller_path(seller), class: "small button success" %>
                <% if seller.status == true %>
                <%= link_to 'Deshabilitar', seller, method: :delete, class: "small button alert",data: { confirm: 'Estas seguro de deshabilitar este vendedor?'} %>
                <%else%>
                <%= link_to 'Habilitar', seller, method: :delete, class: "small button success"%>
                <%end%>

            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>

    <div class="small-4 large-centered columns">
      <%= link_to "Crear Vendedor", new_seller_path, class: "radius button center"%>  </div>
    </div>
</div>
<%end%>
</div>

app/views/sellers/new.html.erb
<div class="panel ">
	<div class="row">
		<div class="large-12 columns">
			<h2>Nuevo vendedor</h2>
		</div>

		<%= render 'form' %>
		<div class="row">
			<div class="small-8 large-centered columns">
				<h8 class="subheader"><i align='center'>La contraseña asignada de forma predeterminada para vendedor sera nombre.apellido</i></h8>
			</div>
			<%= link_to '← Volver', sellers_path %>
		</div>
	</div>

app/views/sellers/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="row">



      <div class="large-12 columns">
        <div class="panel radius">

          <div class="row">
            <div class="large-4 small-4 columns">

              <h4>
                Vendedor - <%= @seller.personId %> - <% if @seller.status == true%> Habilitado <% else %> Deshabilitado <% end %>
              </h4>
              <hr/>

              <h5>
                Nombre
              </h5>            
              <h5 class="subheader">
                <%= @seller.username %> <%= @seller.userLastName %>
              </h5>

              <h5>
                Documento
              </h5>
              <h5 class="subheader">
                <%= @seller.document %>
              </h5>

              <h5>
                Telefono
              </h5>
              <h5 class="subheader">
                <%= @seller.telephone %>
              </h5> 

              <h5>
                Correo Electronico
              </h5>
              <h5 class="subheader">
                <%= @seller.email %>
              </h5>
              <%= link_to 'Editar', edit_seller_path(@seller) , class: "radius button center"%>  
            </div>

            <div class="large-8 small-8 columns">

              <h4 align='center'>
                Ventas
              </h4>
              <%if @sales.empty?  %>
              <p>            </p>
              <div class="row">
                <div class="small-8 large-centered columns">
                  <h4 class ="subheader">Aun no se ha registrado ninguna venta</h4>
                </div>
              </div>
              <%else%>
              <div class="small-12 large-centered columns">
                <table>
                  <thead>
                    <tr>
                      <th width="20">Id</th>
                      <th width="50">Vendedor</th>
                      <th width="50">Cliente</th>
                      <th width="20">Fecha</th>
                      <th>Salestatus</th>
                      <th>Observaciones</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @sales.each do |sale| %>
                    <tr>
                      <td><%= sale.saleId %></td>
                      <td><%= sale.sellerId %></td>
                      <td><%= sale.clientId %></td>
                      <td><%= sale.saleDate %></td>
                      <td><%= sale.saleStatus %></td>
                      <td><%= sale.note %></td>
                      <td><%= link_to 'Show', sale %></td>
                      <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
                      <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <br>
              <% end %>
            </div>

          </div>
        </div>
      </div>

      <%if false%>
      <%= link_to 'Editar', edit_seller_path(@seller) %> |
      <%end%>
      <%= link_to '← Volver', sellers_path %>