config/routes.rb
Rails.application.routes.draw do
  get 'home/salud'

 get 'bike/index'
 
 get 'accesory_part/index'

 get 'bike/index'

 resources :products

 resources :sellers

 resources :sellers

  devise_for :users, :controllers =>{:registrations =>"my_devise/registrations"}

  root to: 'home#index'
  
  get 'catalog/index'
  
  resources :products

  resources :inventories

  resources :sales

  resources :items

  resources :clients

  resources :contract_histories

  resources :articles

  resources :equipment

  resources :bikes

  resources :accesory_parts

  get "/:page" => "static_controller#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_length_of :articleTitle, :within => 1..50
	validates_length_of :body, :within => 1..10000
	validates_length_of :summary, :within => 1..5000
end

app/models/client.rb
class Client < ActiveRecord::Base
	validates_uniqueness_of :personId, :message => "El identificador para esta persona ya existe"
	validates_uniqueness_of :document, :message => "El documento de esa persona ya existe"
	validates_length_of :personName, :within => 1..50
	validates_length_of :document, :within => 7..11
	validates_length_of :lastName, :within => 1..50
	validates_length_of :telephone, :within => 6..20
	def dataClients
		"#{document}: #{personName} #{lastName}"
	end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_uniqueness_of :productId, :message => "El identificador para esta persona ya existe"
	validates_length_of :productReference, :within => 1..10
	validates_length_of :productName, :within => 1..50
	validates_length_of :productTradeMark, :within => 1..50
	validates_length_of :productDescription, :within => 1..300
	#validates_length_of :measures, :within => 1..50
	#validates_length_of :bikeType, :within => 1..50
	validates_presence_of :image , :message => " Debes subir una imagen"
	#validates_length_of :typeProduct, :within => 1..10
	#validates_length_of :size, :within => 1..2
	#validates_length_of :gender, :within => 1..1
	
	has_attached_file :image, :styles => { :small => "220x220#" , :medium => "250x250#" }
	#validates_attachment :image, presence: true, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	#validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
	validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates_length_of :note, :within => 1..300
end

app/models/seller.rb
class Seller < ActiveRecord::Base


  validates_presence_of :username, :message => " no puede ser un campo vacio"
  validates_presence_of :userLastName, :message => " no puede ser un campo vacio"
  validates_presence_of :document , :message => " no puede ser un campo vacio"
  validates_uniqueness_of :document , :message => " ya ha sido registrado "
  validates_length_of :document, :within => 8..11 
  validates_presence_of :telephone, :message => " no puede ser un campo vacio"
  validates_length_of :telephone, :within => 6..20
  validates_presence_of :email, :message => " no puede ser un campo vacio"
  validates_presence_of :password, :message => " no puede ser un campo vacio"


	def dataSellers
		"#{document}: #{username}  #{userLastName}"
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates_presence_of :username, :message => " no puede ser un campo vacio"
  validates_presence_of :userLastName, :message => " no puede ser un campo vacio"
  validates_presence_of :document , :message => " no puede ser un campo vacio"
  validates_uniqueness_of :document , :message => " ya ha sido registrado "
  validates_length_of :document, :within => 8..11 
  validates_presence_of :telephone, :message => " no puede estar vacio"
  validates_length_of :telephone, :within => 6..20
  
  def user_params
      params.require(:user).permit(:username,:userLastName, :document, :telephone, :userType, :status, :email, :password, :password_confirmation)
  end
  def active_for_authentication?
    #remember to call the super
    #then put our own check to determine "active" state using 
    #our own "is_active" column
    super and self.status?
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy]
	respond_to :html, :xml, :json

	before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]
	def index
		@products = Product.all
		respond_to do |format|
			format.html
			format.pdf do
				generateReports(@products)
			end
		end
	end

	def show

	end

	def new
		@product = Product.new
	end

	def edit
	end

	def create

	end

	def update
		respond_to do |format|
			if @product.update(product_params)
				format.html { redirect_to @product, notice: 'La bicibleta se ha modificado satisfactoriamente.' }
				format.json { render :show, status: :ok, location: @product }
			else
				format.html { render :edit }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		respond_to do |format|
			if @product.productStatus==true
				format.html { redirect_to products_url, notice: 'La bicicleta ha sido deshabilitada.' }
				@product.productStatus=false
			else
				format.html { redirect_to products_url, notice: 'La bicicleta ha sido habilitada.' }
				@product.productStatus=true
			end
			format.json { head :no_content }
		end
		@product.save
	end

	private
	def set_product
		@product = Product.find(params[:id])
	end

	def product_params
		params.require(:product).permit(:productId, :productReference, :productName, :productTradeMark, :productPrice, :productStatus, :productDescription, :size, :gender, :image, :typeProduct)
	end

	def generateReports(elements)
		pdf = PDF::Writer.new
		pdf.select_font "Times-Roman"
		pdf.image "public/images/logo.jpg", :justification => :center, :resize => 0.4
		pdf.text "Reporte de Bicicletas", :font_size => 40, :justification => :center
		pdf.text "Generado el "+ (Time.now()).strftime(" %b %d, %Y").to_s, :font_size => 15, :justification => :center
		elements.each do |item|  
			pdf.text "______________________________________________________", :font_size=>20 , :justification => :center
			pdf.text " "
			pdf.text "ID PRODUCTO: "+ item.productId.to_s, :font_size =>15
			pdf.text "REFERENCIA: "+item.productReference.to_s, :font_size => 15
			pdf.text "NOMBRE: " +item.productName.to_s, :font_size => 15
			pdf.text "MARCA: "+ item.productTradeMark.to_s, :font_size => 15
			pdf.text "PRECIO: "+ item.productPrice.to_s, :font_size => 15
			pdf.text "TIPO BICICLETA: "+ item.bikeType.to_s, :font_size => 15
			pdf.text "MEDIDAS: "+ item.measures.to_s, :font_size => 15
			pdf.text "DESCRIPCION: "+item.productDescription, :font_size => 15, :justification => :justify
			if item.productStatus==true 
				pdf.text "ESTADO: Habilitada", :font_size => 15, :justification => :rigth
			else
				pdf.text "ESTADO: Deshabilitada", :font_size => 15, :justification => :rigth
			end

		end
		pdf.render
		send_data pdf.render, :filename => 'Bicicletas.pdf', :type => 'application/pdf', :disposition => 'inline'

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bike_helper.rb
module BikeHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div data-alert class="alert-box alert radius">
      #{messages}
      <a href="#" class="close">&times;</a>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/bikes/_form.html.erb
<%= form_for(@product, html: {:multipart => true}) do |f| %>
<% if @product.errors.any? %>
<div class="row">
  <div class="small-8 large-centered columns">
    <div data-alert class="alert-box alert radius">
      <%= pluralize(@product.errors.count, "error") %> no permite guardar la información de la bicicleta
      <ul>
        <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <a href="#" class="close">&times;</a>
    </div>
  </div>
</div>
<% end %>

<%= f.hidden_field :typeProduct , :value => 'BIKE' %>
<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Referencia</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :productReference , autofocus: true, :required =>true, :maxlength => 10%>
      </div>
    </div>
  </div>
</div>
<br>


<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Nombre de bicicleta</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :productName , :required =>true, :maxlength => 50%>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Marca</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :productTradeMark , :required=>true, :maxlength =>50%>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Precio</label>
      </div>
      <div class="small-9 columns">
        <%= f.number_field :productPrice , :required =>true ,:maxlength => 10 %>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Descripcion</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :productDescription, :required =>true, :maxlength =>300 %>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Medidas</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :measures, :required=>true, :maxlength =>50 %>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Tipo</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :bikeType, :required=>true, :maxlength=>50 %>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Imagen</label>
      </div>
      <div class="small-9 columns">
        <%= f.file_field :image, :required=>true %>
      </div>
    </div>
  </div>
</div>
<br>


<div class="row">
  <div class="small-4 large-centered columns"><%= f.submit "Guardar", class: "button success radius" %>
  </div>
</div>

<% end %>

app/views/bikes/edit.html.erb
<div class="panel ">
	<h1>Editar bicicleta</h1>

	<%= form_for(@product, html: {:multipart => true}) do |f| %>
	<% if @product.errors.any? %>
	<div class="row">
		<div class="small-8 large-centered columns">
			<div data-alert class="alert-box alert radius">
				<%= pluralize(@product.errors.count, "error") %> no permite guardar la información de la bicicleta
				<ul>
					<% @product.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
				<a href="#" class="close">&times;</a>
			</div>
		</div>
	</div>
	<% end %>

	<%= f.hidden_field :typeProduct , :value => 'BIKE' %>
	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Referencia</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :productReference , autofocus: true, :required =>true, :maxlength => 10%>
				</div>
			</div>
		</div>
	</div>
	<br>


	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Nombre de bicicleta</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :productName , :required =>true, :maxlength => 50%>
				</div>
			</div>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Marca</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :productTradeMark , :required=>true, :maxlength =>50%>
				</div>
			</div>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Precio</label>
				</div>
				<div class="small-9 columns">
					<%= f.number_field :productPrice , :required =>true ,:maxlength => 10 %>
				</div>
			</div>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Descripcion</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :productDescription, :required =>true, :maxlength =>300 %>
				</div>
			</div>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Medidas</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :measures, :required=>true, :maxlength =>50 %>
				</div>
			</div>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Tipo</label>
				</div>
				<div class="small-9 columns">
					<%= f.text_field :bikeType, :required=>true, :maxlength=>50 %>
				</div>
			</div>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="small-8">
			<div class="row">
				<div class="small-3 columns">
					<label for="right-label" class="right inline">Imagen</label>
				</div>
				<div class="small-9 columns">
					<label><i>Si no desea modificar la imagen de este producto, no seleccione ningun archivo</i></label>
					<%= f.file_field :image%>
				</div>
			</div>
		</div>
	</div>
	<br>


	<div class="row">
		<div class="small-4 large-centered columns"><%= f.submit "Guardar", class: "button success radius" %>
		</div>
	</div>

	<% end %>




	<%= link_to '← Volver', bikes_path %>
</div>

app/views/bikes/index.html.erb
<%if user_signed_in?%>

<div class="panel">
  <%if @products.empty?  %>
  <p>            </p>
  <div class="row">
    <div class="small-8 large-centered columns">
      <h1 align="center">Aun no se ha registrado ninguna bicicletax</h1>
    </div>
    <div class="small-2 large-centered columns">
      <%if user_signed_in? && current_user.userType == "Seller"%>
      <%= link_to 'Nueva Bicicleta', new_bike_path , class: "radius button center"%> 
      <% end %>
    </div>
  </div>
  <%else%>
  <div class="row">
    <div class="small-12 large-centered columns">
      <h1>Lista de Bicicletas - La Ciclería</h1>
    </div>
    <div class="large-centered columns">

      <table>
        <thead>
          <tr>
            <th>Id</th>
            <th>Referencia</th>
            <th>Producto</th>
            <th>Marca</th>
            <th>Precio</th>
            <th>Descripcion</th>
            <th>Medidas</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
          <tr>
            <% if product.typeProduct == 'BIKE'%>
            <td><%= product.productId %></td>
            <td><%= product.productReference %></td>
            <td><%= product.productName %></td>
            <td><%= product.productTradeMark %></td>
            <td><%= product.productPrice %></td>
            <td><%= product.productDescription %></td>
            <td><%= product.measures %></td>
            <td>
              <%= link_to 'Ver', bike_path(product) , class: "small button success centered"%>
              <%= link_to 'Editar', edit_bike_path(product), class: "small button success" %>
              <% if product.productStatus == true %>
              <%= link_to 'Deshabilitar', product, method: :delete, class: "small button alert",data: { confirm: 'Estas seguro de deshabilitar esta bicicleta?'} %>
              <%else%>
              <%= link_to 'Habilitar', product, method: :delete, class: "small button success"%>
              <%end%>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

      <br>
    </div>
    <br>
    <div class="small-4 large-centered columns">
      <%if user_signed_in? && current_user.userType == "Seller"%>
      <%= link_to 'Nueva Bicicleta', new_bike_path , class: "radius button center"%> 
      <% end %>

      <%if user_signed_in? && current_user.userType == "Manager"%>
      <%= link_to 'Generar Reporte', bikes_path(:pdf) , class: "radius button center"%>
      <% end %>
    </div>
  </div>
</div>
<%end%>
</div>

<% else %>

<div class="row">
  <div class="large-12 columns">
    <div class="hide-for-small">
      <div id="featured">
        <img src="/images/parked-bike3.jpg" alt="Bicis">
      </div>
    </div>



    <div class="row">
      <div class="small-12 show-for-small"><br>
        <img src="/images/parked-bike3.jpg"/>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="large-12 columns">
    <h2 align="center">BICICLETAS</h2>
    <div class="row">

      <% @products.each do |product| %>
      <% if product.typeProduct == 'BIKE'%>

      <div class="large-3 small-6 columns">
        <%= image_tag product.image.url (:medium)%>
        <div class="panel">
          <h6><%= product.productName %></h6>
          <p><%= product.productTradeMark %> - <%= product.productPrice %> COP</p>
          <%= link_to 'Ver más', bike_path(product) , class: "small button center"%>
        </div>
      </div>

      <% end %>
      <% end %>
    </div>
  </div>
</div>


<% end %>

app/views/bikes/new.html.erb
<div class="panel ">
<div class="row">
	<div class="large-8 columns">
		<h2>Nueva Bicicleta </h2>
	</div>
</div>
<%= render 'form' %>


<div class="row">
	<div class="large-9 columns">
		<div class="actions">
			<%= link_to '← Volver', bikes_path %>
		</div>
	</div>
</div>

</div>

app/views/bikes/show.html.erb
<br>
<br>
<br>
<div class="row">

  <div class="large-6 columns">
    <%= image_tag @product.image.url%>
  </div>
  <div id="myModal" class="reveal-modal" data-reveal>
    <%= image_tag @product.image.url%>
    <a class="close-reveal-modal">&#215;</a>
  </div>

  <div class="large-6 columns">

    <h3 class="show-for-small">Header<hr/></h3>

    <div class="panel">
      <h4 class="hide-for-small"><%= @product.productTradeMark %> - <%= @product.productName %> (<%= @product.typeProduct %>)<hr/></h4>
      <h5 class="subheader"><%= @product.productDescription %></h5>
      <h5 class="subheader"><strong>Medidas: </strong><%= @product.measures %></h5>
      <h5 class="subheader"><strong>Precio:</strong> <%= @product.productPrice %> COP$</h5>
    </div>
    <a href="" data-reveal-id="myModal" align="center"><i class="fi-zoom-in size-72"> Zoom</i></a>
    <div class="row">
      <div class="large-6 small-6 columns">
        <div class="panel">
          <h5>Referencia</h5>
          <h6 class="subheader"><%= @product.productReference %></h6>
          <%= link_to '← Volver', bikes_path%>
        </div>
      </div>

      <%if user_signed_in? && current_user.userType == "Seller"%>
      <div class="large-6 small-6 columns">
        <div class="panel">
          <h5>Id - Estado</h5>
          <h6 class="subheader">
            <%= @product.productId %> -
            <%if @product.productStatus == true %>
            Habilitado
            <%else%>
            Deshabilitado
            <%end%>
          </h6>
          <%= link_to 'Editar', edit_bike_path(@product) , class: "small button success radius"%> 
        </div>
      </div>
      <%end%>
    </div>

  </div>

</div>