config/routes.rb
Rails.application.routes.draw do
  get 'home/salud'

 get 'bike/index'
 
 get 'accesory_part/index'

 get 'bike/index'

 resources :products

 resources :sellers

 resources :sellers

  devise_for :users, :controllers =>{:registrations =>"my_devise/registrations"}

  root to: 'home#index'
  
  get 'catalog/index'
  
  resources :products

  resources :inventories

  resources :sales

  resources :items

  resources :clients

  resources :contract_histories

  resources :articles

  resources :equipment

  resources :bikes

  resources :accesory_parts

  get "/:page" => "static_controller#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_length_of :articleTitle, :within => 1..50
	validates_length_of :body, :within => 1..10000
	validates_length_of :summary, :within => 1..5000
end

app/models/client.rb
class Client < ActiveRecord::Base
	validates_uniqueness_of :personId, :message => "El identificador para esta persona ya existe"
	validates_uniqueness_of :document, :message => "El documento de esa persona ya existe"
	validates_length_of :personName, :within => 1..50
	validates_length_of :document, :within => 7..11
	validates_length_of :lastName, :within => 1..50
	validates_length_of :telephone, :within => 6..20
	def dataClients
		"#{document}: #{personName} #{lastName}"
	end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_uniqueness_of :productId, :message => "El identificador para esta persona ya existe"
	validates_length_of :productReference, :within => 1..10
	validates_length_of :productName, :within => 1..50
	validates_length_of :productTradeMark, :within => 1..50
	validates_length_of :productDescription, :within => 1..300
	#validates_length_of :measures, :within => 1..50
	#validates_length_of :bikeType, :within => 1..50
	validates_presence_of :image , :message => " Debes subir una imagen"
	#validates_length_of :typeProduct, :within => 1..10
	#validates_length_of :size, :within => 1..2
	#validates_length_of :gender, :within => 1..1
	
	has_attached_file :image, :styles => { :small => "220x220#" , :medium => "250x250#" }
	#validates_attachment :image, presence: true, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	#validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
	validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates_length_of :note, :within => 1..300
end

app/models/seller.rb
class Seller < ActiveRecord::Base


  validates_presence_of :username, :message => " no puede ser un campo vacio"
  validates_presence_of :userLastName, :message => " no puede ser un campo vacio"
  validates_presence_of :document , :message => " no puede ser un campo vacio"
  validates_uniqueness_of :document , :message => " ya ha sido registrado "
  validates_length_of :document, :within => 8..11 
  validates_presence_of :telephone, :message => " no puede ser un campo vacio"
  validates_length_of :telephone, :within => 6..20
  validates_presence_of :email, :message => " no puede ser un campo vacio"
  validates_presence_of :password, :message => " no puede ser un campo vacio"


	def dataSellers
		"#{document}: #{username}  #{userLastName}"
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates_presence_of :username, :message => " no puede ser un campo vacio"
  validates_presence_of :userLastName, :message => " no puede ser un campo vacio"
  validates_presence_of :document , :message => " no puede ser un campo vacio"
  validates_uniqueness_of :document , :message => " ya ha sido registrado "
  validates_length_of :document, :within => 8..11 
  validates_presence_of :telephone, :message => " no puede estar vacio"
  validates_length_of :telephone, :within => 6..20
  
  def user_params
      params.require(:user).permit(:username,:userLastName, :document, :telephone, :userType, :status, :email, :password, :password_confirmation)
  end
  def active_for_authentication?
    #remember to call the super
    #then put our own check to determine "active" state using 
    #our own "is_active" column
    super and self.status?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  before_filter :authenticate_user!
  def index
    @items = Item.all
    
  end

  def show

  end

  def new
    @item = Item.new
    @products=Product.where(:productStatus => 1)
    query="select p.productName, p.productReference, i.itemAmount, i.id from products p, items i where p.productId=i.productId and i.saleId=#{params[:saleId]}"
    @items=ActiveRecord::Base.connection.execute(query)
    @saleId=params[:saleId]
    
    
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    #@item.saleId =@saleId  
    @item.save
    respond_to do |format|
      if @item.save
        format.html { redirect_to new_item_path(:saleId => @item.saleId) }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item modificado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to new_item_path(:saleId => @item.saleId) }
      format.json { head :no_content }
    end
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:saleId, :productId, :itemAmount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bike_helper.rb
module BikeHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div data-alert class="alert-box alert radius">
      #{messages}
      <a href="#" class="close">&times;</a>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
<% if @item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

  <ul>
    <% @item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="large-6 columns">
    <%= f.hidden_field :saleId, :value => @saleId%>
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Vendedor</label>
      </div>
      <div class="small-9 columns">
        <label for="left-label" class="left inline"><%=current_user.username%> <%=current_user.userLastName%></label>
      </div>
    </div>


    
    <br>



    <div class="row">
      <div class="large-3 columns">
        <label for="right-label" class="right inline">Fecha venta</label>
      </div>
      <div class="large-9 columns">
        <label for="left-label" class="left inline"><%=Time.now%></label>
      </div>
    </div>

    
    <br>



    <div class="row">
      <div class="large-3 columns">
        <label for="right-label" class="right inline">Producto</label>
      </div>
      <div class="large-9 columns">
        <%= f.collection_select :productId, @products, :productId, :productName, :required =>true %>
      </div>
    </div>

    
    <br>
    <br>

    <div class="row">
      <div class="large-3 columns">
        <label for="right-label" class="right inline">Cantidades</label>
      </div>
      <div class="large-9 columns">
        <%= f.number_field :itemAmount, :required =>true %>
      </div>
    </div>

    <br>
    <br>
    <div class="row">
      <div class="large-6 columns"><%= f.submit "Agregar producto", class: "radius button center"%>
      </div>
      <div class="large-6 columns">
        <%= link_to 'Finalizar venta', sale_path(:id =>@saleId), class: "radius button center" %>
      </div>
    </div>
  </div>

  <div class="large-6 columns">
    <div class="row">
      <div class="medium-6 medium-push-6 columns">
        <h5 align='center'>Lista de productos en esta compra</h5>
      </div>

      <div class="medium-6 medium-push-6 columns">
        <!--Tabla de productos -->
        <table>
          <thead>
            <tr>
              
              <th width="300">Nombre producto</th>
              <th width="300">Referencia</th>
              <th width="30">Cantidad</th>
            </tr>
          </thead>
          <tbody>
            <tr>
             <% @items.each do |item| %>
             <tr>
              <td><%= item[0]%></td>
              <td><%= item[1]%></td>
              <td><%= item[2]%></td>
              <td><%= link_to 'Remover', item_path(item[3]), method: :delete, data: { confirm: 'Desea remover este producto?' } %>
              <%end%>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
      <br>

      


    </div>
  </div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Saleid</th>
      <th>Productid</th>
      <th>Itemamount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.saleId %></td>
      <td><%= item.productId %></td>
      <td><%= item.itemAmount %></td>
      <td><%= link_to 'Show', item %></td>
      <td><%= link_to 'Edit', edit_item_path(item) %></td>
      <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<div class="panel ">
	<div class="row">
		<div class="large-8 columns">
			<h2>Seleccion de Productos </h2>
			<h7 >Creacion de venta 2/2</h7>
			<br>
			<br><br>
		</div>
		
	</div>

	<%= render 'form' %>
	<br>
	
	<div class="row">
		<div class="medium-4 columns">
			<div class="actions">
				<br>
				<%= link_to '← Volver', sales_path %>
			</div>
		</div>
	</div>
	<br>
</div>
</div>

app/views/items/show.html.erb
<br>
<br>
<br>
<div class="row">

  <div class="large-6 columns">
      tabla
  </div>

  <div class="large-6 columns">

    <h3 class="show-for-small">Header<hr/></h3>

    <div class="panel">
      <h4 class="hide-for-small">Venta # <%= @sale.saleId%> - La cicleria cafe taller<hr/></h4>
      <h5 class="subheader"><%= @sale.note %></h5>
      <h5 class="subheader"><strong>Vendedor: </strong><%= @sale.sellerId %></h5>
      <h5 class="subheader"><strong>Fecha de venta:</strong> <%= @sale.saleDate %></h5>
    </div>

    <div class="row">
      <div class="large-6 small-6 columns">
        <div class="panel">
          <h5>Cliente</h5>
          <h6 class="subheader"><%= @sale.clientId %></h6>
          <%= link_to '← Volver', sales_path%>
        </div>
      </div>

      <%if user_signed_in? && current_user.userType == "Seller"%>
      <div class="large-6 small-6 columns">
        <div class="panel">
          <h5>Id - Estado</h5>
          <h6 class="subheader">
            <%= @sale.saleId %> -
            <%if @sale.saleStatus == true %>
            Habilitado
            <%else%>
            Deshabilitado
            <%end%>
          </h6>
          <%= link_to 'Editar no sirve', edit_bike_path(@product) , class: "small button success radius"%> 
        </div>
      </div>
      <%end%>
    </div>

  </div>

</div>