config/routes.rb
Rails.application.routes.draw do
  get 'home/salud'

 get 'bike/index'
 
 get 'accesory_part/index'

 get 'bike/index'

 resources :products

 resources :sellers

 resources :sellers

  devise_for :users, :controllers =>{:registrations =>"my_devise/registrations"}

  root to: 'home#index'
  
  get 'catalog/index'
  
  resources :products

  resources :inventories

  resources :sales

  resources :items

  resources :clients

  resources :contract_histories

  resources :articles

  resources :equipment

  resources :bikes

  resources :accesory_parts

  get "/:page" => "static_controller#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_length_of :articleTitle, :within => 1..50
	validates_length_of :body, :within => 1..10000
	validates_length_of :summary, :within => 1..5000
end

app/models/client.rb
class Client < ActiveRecord::Base
	validates_uniqueness_of :personId, :message => "El identificador para esta persona ya existe"
	validates_uniqueness_of :document, :message => "El documento de esa persona ya existe"
	validates_length_of :personName, :within => 1..50
	validates_length_of :document, :within => 7..11
	validates_length_of :lastName, :within => 1..50
	validates_length_of :telephone, :within => 6..20
	def dataClients
		"#{document}: #{personName} #{lastName}"
	end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_uniqueness_of :productId, :message => "El identificador para esta persona ya existe"
	validates_length_of :productReference, :within => 1..10
	validates_length_of :productName, :within => 1..50
	validates_length_of :productTradeMark, :within => 1..50
	validates_length_of :productDescription, :within => 1..300
	#validates_length_of :measures, :within => 1..50
	#validates_length_of :bikeType, :within => 1..50
	validates_presence_of :image , :message => " Debes subir una imagen"
	#validates_length_of :typeProduct, :within => 1..10
	#validates_length_of :size, :within => 1..2
	#validates_length_of :gender, :within => 1..1
	
	has_attached_file :image, :styles => { :small => "220x220#" , :medium => "250x250#" }
	#validates_attachment :image, presence: true, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	#validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
	validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates_length_of :note, :within => 1..300
end

app/models/seller.rb
class Seller < ActiveRecord::Base


  validates_presence_of :username, :message => " no puede ser un campo vacio"
  validates_presence_of :userLastName, :message => " no puede ser un campo vacio"
  validates_presence_of :document , :message => " no puede ser un campo vacio"
  validates_uniqueness_of :document , :message => " ya ha sido registrado "
  validates_length_of :document, :within => 8..11 
  validates_presence_of :telephone, :message => " no puede ser un campo vacio"
  validates_length_of :telephone, :within => 6..20
  validates_presence_of :email, :message => " no puede ser un campo vacio"
  validates_presence_of :password, :message => " no puede ser un campo vacio"


	def dataSellers
		"#{document}: #{username}  #{userLastName}"
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates_presence_of :username, :message => " no puede ser un campo vacio"
  validates_presence_of :userLastName, :message => " no puede ser un campo vacio"
  validates_presence_of :document , :message => " no puede ser un campo vacio"
  validates_uniqueness_of :document , :message => " ya ha sido registrado "
  validates_length_of :document, :within => 8..11 
  validates_presence_of :telephone, :message => " no puede estar vacio"
  validates_length_of :telephone, :within => 6..20
  
  def user_params
      params.require(:user).permit(:username,:userLastName, :document, :telephone, :userType, :status, :email, :password, :password_confirmation)
  end
  def active_for_authentication?
    #remember to call the super
    #then put our own check to determine "active" state using 
    #our own "is_active" column
    super and self.status?
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  before_filter :authenticate_user!
  def index
    query="select distinct(s.saleId), (select concat(username,'  ', userLastName) from sellers where personId=s.sellerId), (select concat(personName, ' ', lastName) from clients where personId=s.clientId), s.saleDate, s.note, s.saleStatus from sales s, items i where s.saleId=i.saleId"
    @sales=ActiveRecord::Base.connection.execute(query)
  end

  def show
    @client=Client.where(:personId =>@sale.clientId)
    @seller=Seller.where(:personId =>@sale.sellerId)
    query="select p.productName, p.productReference, i.itemAmount from products p, items i where p.productId=i.productId and i.saleId=#{@sale.saleId}"
    @items=ActiveRecord::Base.connection.execute(query)
  end

  def new
    @sale = Sale.new
    @sellers=Seller.all
    @clients=Client.all
  end

  def edit
    @sellers=Seller.all
    @clients=Client.all
  end

  def create
    @sale = Sale.new(sale_params)
    if Sale.all.nil?
      @sale.saleId=1
    else
      @sale.saleId = Sale.all.count+1
    end
    @sale.saleStatus=true
    @sale.save
    respond_to do |format|
      if @sale.save
        format.html { redirect_to new_item_path(:saleId => @sale.saleId) }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Venta modificada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    #@sale.destroy
    respond_to do |format|
      if @sale.saleStatus==true
        format.html { redirect_to sales_path, notice: 'Venta deshabilitada.' }
        @sale.saleStatus=false
      else 
        format.html { redirect_to sales_path, notice: 'La venta se ha habilitado.' }
        @sale.saleStatus=true
        format.json { head :no_content }
      end
      @sale.save
    end
  end

  private
  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:saleId, :sellerId, :clientId, :saleDate, :saleStatus, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bike_helper.rb
module BikeHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div data-alert class="alert-box alert radius">
      #{messages}
      <a href="#" class="close">&times;</a>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
<% if @sale.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

  <ul>
    <% @sale.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= f.hidden_field :sellerId, :value => current_user.personId%>
<%= f.hidden_field :saleDate, :value => Time.now%>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Cliente</label>
      </div>
      <div class="small-9 columns">
        <%= f.collection_select :clientId, @clients, :personId, :dataClients, :required =>true %>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <label for="right-label" class="right inline">Observaciones</label>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :note, :required=>true, :maxlength =>300 %>
      </div>
    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="small-4 large-centered columns"><%= f.submit "Siguiente", class: "radius button center"%>
  </div>

<% end %>

app/views/sales/edit.html.erb
<div class="panel ">
	<div class="row">
		<div class="large-8 columns">
			<h2>Editar venta </h2>
			<br>
			<br><br>
		</div>
	</div>


	<%= render 'form' %>

	<div class="row">
		<div class="large-9 columns">
			<div class="actions">
				<%= link_to '← Volver', sales_path %>
			</div>
		</div>
	</div>
</div>

app/views/sales/index.html.erb
<div class="panel">
  <%if @sales.nil?  %>
  <p>            </p>
  <div class="row">
    <div class="small-8 large-centered columns">
      <h1 align="center">Aun no se ha registrado ninguna venta</h1>
    </div>
  </div>
  <%else%>
  <div class="row">
    <div class="small-12 large-centered columns">
      <h1>Lista de ventas - La Ciclería</h1>
    </div>
    <div class="small-12 large-centered columns">
      <table>
        <thead>
          <tr>
            <th width="6">Id de Venta</th>
            <th width="100">Nombre Vendedor</th>
            <th width="100">Nombre Cliente</th>
            <th width="50">Fecha</th>
            <th width="100">Observaciones</th>
            <th colspan="3"> Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @sales.each do |sale| %>
          <tr>
            <td><%= sale[0]%></td>
            <td><%= sale[1] %></td>
            <td><%= sale[2] %></td>
            <td><%= sale[3] %></td>
            <td><%= sale[4] %></td>
            <td><%= link_to 'Ver',sale_path(:id =>sale[0]), class: "small button success"%>
              <%= link_to 'Editar', edit_sale_path(:id =>sale[0]), class: "small button success" %>
              <% if sale[5] == 1 %>
              <%= link_to 'Deshabilitar', sale_path(:id=>sale[0]), method: :delete, class: "small button alert", data: { confirm: '¿Estas seguro de deshabilitar esta venta?' }%>
              <% else %>
              <%=link_to "Habilitar", sale_path(:id=>sale[0]), method: :delete, class: "small button success"%>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
    <% if current_user.userType == 'Seller' %>
      <div class="small-4 large-centered columns"><%= link_to "Crear Venta", new_sale_path, class: "button success radius"%>  </div>
    <% end %>

  </div>
</div>
<%end%>
</div>

app/views/sales/new.html.erb
<div class="panel ">
	<div class="row">
		<div class="large-8 columns">
			<h2>Nueva venta </h2>
			<h7 >Creacion de venta 1/2</h7>
			<br>
			<br><br>
		</div>
	</div>
	<% if @clients.empty?%>
	<div class="row">
		<div class="large-8 columns">
			<h3>Aún no se ha registrado ningun cliente</h3>
			<% if current_user.userType=='Seller' %> 
			<%= link_to 'Nuevo Cliente',new_client_path , class: "radius button center" %> 
		</div>
	</div>
	<% end %>
	<% else%>
	<%= render 'form' %>
	<% end %>



</div>
<div class="row">
	<div class="large-9 columns">
		<div class="actions">
			<%= link_to '← Volver', sales_path %>
		</div>
	</div>
</div>

app/views/sales/show.html.erb
<br>
<br>
<br>
<div class="row">

  <div class="large-6 columns">
    <br>
    <br>
    <br>
    <table>
      <thead>
        <tr>
          <th width="300">Nombre producto</th>
          <th width="300">Referencia</th>
          <th width="30"> Cantidad</th>
        </tr>
      </thead>
      <tbody>
        <tr>
         <% @items.each do |item| %>
         <tr>
          <td><%= item[0] %></td>
          <td><%= item[1]%></td>
          <td><%= item[2]%></td>
          <% end %>      

        </tr>
      </tbody>
    </table>
    <br>


  </div>

  <div class="large-6 columns">

    <h3 class="show-for-small">Header<hr/></h3>

    <div class="panel">
      <h4 class="hide-for-small">Venta # <%= @sale.saleId%> - La cicleria cafe taller<hr/></h4>
      <h5 class="subheader"><%= @sale.note %></h5>
      <h5 class="subheader"><strong>Vendedor: </strong>
        <% @seller.each do |seller| %>
        <%=seller.username %> <%=seller.userLastName %></h5>
        <% end %>
        <h5 class="subheader"><strong>Fecha de venta:</strong> <%= @sale.saleDate %></h5>
      </div>

      <div class="row">
        <div class="large-6 small-6 columns">
          <div class="panel">
            <h5>Cliente</h5>
            <h6 class="subheader">
              <% @client.each do |client| %>
              <%=client.personName %> <%=client.lastName %></h5>
              <% end %>

            </h6>
            <%= link_to '← Volver', sales_path%>
          </div>
        </div>

        <%if user_signed_in? && current_user.userType == "Seller"%>
        <div class="large-6 small-6 columns">
          <div class="panel">
            <h5>Id - Estado</h5>
            <h6 class="subheader">
              <%= @sale.saleId %> -
              <%if @sale.saleStatus == true %>
              Habilitado
              <%else%>
              Deshabilitado
              <%end%>
            </h6>
            <%= link_to 'Editar', edit_sale_path(@sale) , class: "small button success radius"%> 
          </div>
        </div>
        <%end%>
      </div>

    </div>

  </div>